{
 "title": "Kubernetes Deployment 2",
 "description": "Kubernetes deployments overview dashboard",
 "tags": [ "kubernetes" ],
 "time": { "from": "2019-01-30T14:30:26.442Z", "to": "2019-01-30T16:14:21.435Z" },
 "templating": {
  "list": [
   {
    "name": "deployment_namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation, namespace)"
   },
   {
    "name": "deployment_name",
    "label": "Deployment",
    "query": "label_values(kube_deployment_metadata_generation{namespace=\"$deployment_namespace\"}, deployment)"
   },
   {
    "name": "deployment_release",
    "label": "Release",
    "query": "label_values(kube_deployment_labels{namespace=\"$deployment_namespace\",deployment=\"$deployment_name\"}, label_release)"
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n      label_replace(kube_pod_info_ex{owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.+)\")\n      * on (replicaset) group_left (owner_name, owner_kind)\n      kube_replicaset_owner {owner_name=\"$deployment_name\"}, \"pod_name\", \"$1\", \"pod\", \"(.+)\"\n  )\n  * on(pod_name) group_right\n  container_memory_usage_bytes {container_name!=\"POD\"}\n) \n"
    }
   ]
  },
  {
   "title": "Memory Usage Total",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n      label_replace(kube_pod_info_ex{owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.+)\")\n      * on (replicaset) group_left (owner_name, owner_kind)\n      kube_replicaset_owner {owner_name=\"$deployment_name\"}, \"pod_name\", \"$1\", \"pod\", \"(.+)\"\n  )\n  * on(pod_name) group_right\n  container_memory_usage_bytes\n)"
    }
   ]
  },
  {
   "title": "Memory Usage Percentage (Requests)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n      label_replace(kube_pod_info_ex{owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.+)\")\n      * on (replicaset) group_left (owner_name, owner_kind)\n      kube_replicaset_owner {owner_name=\"$deployment_name\"}, \"pod_name\", \"$1\", \"pod\", \"(.+)\"\n  )\n  * on(pod_name) group_right\n  container_memory_usage_bytes\n) \n/\nsum(\n  label_replace(\n      label_replace(kube_pod_info_ex{owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.+)\")\n      * on (replicaset) group_left (owner_name, owner_kind)\n      kube_replicaset_owner {owner_name=\"$deployment_name\"}, \"pod_name\", \"$1\", \"pod\", \"(.+)\"\n  )\n  * on(pod) group_right\n  kube_pod_container_resource_requests_memory_bytes\n) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage Percentage (Limit)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n      label_replace(kube_pod_info_ex{owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.+)\")\n      * on (replicaset) group_left (owner_name, owner_kind)\n      kube_replicaset_owner {owner_name=\"$deployment_name\"}, \"pod_name\", \"$1\", \"pod\", \"(.+)\"\n  )\n  * on(pod_name) group_right\n  container_memory_usage_bytes\n) \n/\nsum(\n  label_replace(\n      label_replace(kube_pod_info_ex{owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.+)\")\n      * on (replicaset) group_left (owner_name, owner_kind)\n      kube_replicaset_owner {owner_name=\"$deployment_name\"}, \"pod_name\", \"$1\", \"pod\", \"(.+)\"\n  )\n  * on(pod) group_right\n  kube_pod_container_resource_limits_memory_bytes\n) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage Per Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "  label_replace(\n      label_replace(kube_pod_info_ex{owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.+)\")\n      * on (replicaset) group_left (owner_name, owner_kind)\n      kube_replicaset_owner {owner_name=\"$deployment_name\"}, \"pod_name\", \"$1\", \"pod\", \"(.+)\"\n  )\n  * on(pod_name) group_right\n  container_memory_usage_bytes {container_name!=\"POD\" }",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Pod",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(\n  label_replace(\n      label_replace(kube_pod_info_ex{owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.+)\")\n      * on (replicaset) group_left (owner_name, owner_kind)\n      kube_replicaset_owner {owner_name=\"$deployment_name\"}, \"pod_name\", \"$1\", \"pod\", \"(.+)\"\n  )\n  * on(pod_name) group_right\n  container_memory_usage_bytes {container_name!=\"POD\"}\n) "
    }
   ]
  },
  {
   "title": "Memory Requests Per Pod",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(\n  label_replace(\n      label_replace(kube_pod_info_ex{owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.+)\")\n      * on (replicaset) group_left (owner_name, owner_kind)\n      kube_replicaset_owner {owner_name=\"$deployment_name\"}, \"pod_name\", \"$1\", \"pod\", \"(.+)\"\n  )\n  * on(pod) group_right\n  kube_pod_container_resource_requests_memory_bytes\n)"
    }
   ]
  },
  {
   "title": "Memory Limit Per Pod",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(\n  label_replace(\n      label_replace(kube_pod_info_ex{owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.+)\")\n      * on (replicaset) group_left (owner_name, owner_kind)\n      kube_replicaset_owner {owner_name=\"$deployment_name\"}, \"pod_name\", \"$1\", \"pod\", \"(.+)\"\n  )\n  * on(pod) group_right\n  kube_pod_container_resource_limits_memory_bytes\n)"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Usage Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "CPU (Millicores)" }
   ],
   "targets": [
    {
     "expr": "sum(\n    label_replace(\n        label_replace(kube_pod_info_ex{owner_kind=\"ReplicaSet\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.+)\")\n        * on (replicaset) group_left (owner_name, owner_kind)\n        kube_replicaset_owner {owner_name=\"$deployment_name\"}, \"pod_name\", \"$1\", \"pod\", \"(.+)\"\n    )\n    * on(pod_name) group_right\n    rate(container_cpu_user_seconds_total {container_name!=\"POD\"}[5m])\n) * 1000",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod_name!=\"\", pod_name=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\", namespace=\"$deployment_namespace\"}[5m])) * 10000"
    }
   ]
  },
  {
   "title": "CPU Usage Percentage (Requests)",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{pod_name!=\"\", pod_name=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\", namespace=\"$deployment_namespace\"}[5m])) * 10000 / (sum(kube_pod_container_resource_requests_cpu_cores * on (namespace, pod) group_left(label_release) kube_pod_labels {pod=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\"}) * 1000))*100"
    }
   ]
  },
  {
   "title": "CPU Usage Percentage (Limit)",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod_name!=\"\", pod_name=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\", namespace=\"$deployment_namespace\"}[5m])) * 10000 / (sum(kube_pod_container_resource_limits_cpu_cores * on (namespace, pod) group_left(label_release) kube_pod_labels {pod=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\"}) * 1000) * 100"
    }
   ]
  },
  {
   "title": "CPU Requests Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores * on (namespace, pod) group_left(label_release) kube_pod_labels {pod=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\"}) * 1000"
    }
   ]
  },
  {
   "title": "CPU Limits Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores * on (namespace, pod) group_left(label_release) kube_pod_labels {pod=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\"}) * 1000"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod_name!=\"\", pod_name=~\"$deployment_name-.*$\", namespace=\"$deployment_namespace\"}[5m]) * 100) by (pod_name)"
    }
   ]
  },
  {
   "title": "CPU Usage Per Pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod_name!=\"\", pod_name=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\", namespace=\"$deployment_namespace\"}[5m])) * 10000"
    }
   ]
  },
  {
   "title": "CPU Limits Per Pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores * on (namespace, pod) group_left(label_release) kube_pod_labels {pod=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\"}) * 1000"
    }
   ]
  },
  {
   "title": "CPU Requests Per Pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores * on (namespace, pod) group_left(label_release) kube_pod_labels {pod=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\"}) * 1000"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Restarts" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"production\",pod=~\"ts-authentication-service-authentication-service.*\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Restarts" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{pod=~\"$deployment_name.*\",namespace=\"$deployment_namespace\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{pod=~\"$deployment_name.*\",namespace=\"$deployment_namespace\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{pod=~\"$deployment_name.*\",namespace=\"$deployment_namespace\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\"$deployment_name.*\",namespace=\"$deployment_namespace\"})",
     "legendFormat": "Running"
    }
   ]
  },
  { "title": "Replicas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Minimum Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 43 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_hpa_spec_min_replicas{hpa=~\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Scale Percentage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 43 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) - max(kube_hpa_spec_min_replicas{hpa=~\"$deployment_name\",namespace=\"$deployment_namespace\"})) / (max(kube_hpa_spec_max_replicas{hpa=~\"$deployment_name\",namespace=\"$deployment_namespace\"}) - max(kube_hpa_spec_min_replicas{hpa=~\"$deployment_name\",namespace=\"$deployment_namespace\"})) * 100"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 12, "y": 43 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Replica Availability",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 43 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) / max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) * 100"
    }
   ]
  },
  {
   "title": "Maximum Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_hpa_spec_max_replicas{hpa=~\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 12, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Network Inbound",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 57 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$deployment_namespace\",pod_name=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\"}[3m]))"
    }
   ]
  },
  {
   "title": "Network Outbound",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 57 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$deployment_namespace\",pod_name=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\"}[3m])) "
    }
   ]
  },
  {
   "title": "Network Combined",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 57 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$deployment_namespace\",pod_name=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$deployment_namespace\",pod_name=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\"}[3m]))"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$deployment_namespace\",pod_name=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\"}[3m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$deployment_namespace\",pod_name=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\"}[3m])) ",
     "legendFormat": "Outbound"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$deployment_namespace\",pod_name=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$deployment_namespace\",pod_name=~\"$deployment_name-[a-z0-9]+-[a-z0-9]+$\"}[3m]))",
     "legendFormat": "Combined"
    }
   ]
  }
 ]
}