{
 "title": "Content Gateway Dashboard",
 "description": "Swagger-Stats Main Dashboard Revision  3",
 "tags": [
  "javascript",
  "typescript",
  "node",
  "express"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(api_all_request_total, service)"
    }
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 }, "options": { "content": "# Content Gateway Canary\n" } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "# Content Gateway Service Production\n"
   }
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_all_request_total{service=\"$service\", pod!~\".*mirror.*\"})"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(api_request_duration_milliseconds_bucket{le=\"25\",code=~\"^2..$\",service=\"$service\",path!=\"/metrics\",path!=\"/health\", pod!~\".*mirror.*\"}[5m]))\n+\n  sum(rate(api_request_duration_milliseconds_bucket{le=\"100\",code=~\"^2..$\",service=\"$service\",path!=\"/metrics\",path!=\"/health\", pod!~\".*mirror.*\"}[5m]))\n) / 2 / sum(rate(api_request_duration_milliseconds_count{service=\"$service\",path!=\"/metrics\",path!=\"/health\", pod!~\".*mirror.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Errors %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_all_errors_total{service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod!~\".*mirror.*\"})/sum(api_all_request_total{service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod!~\".*mirror.*\"})* 100"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_all_request_total{service=\"$service\", pod=~\".*mirror.*\"})"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(api_request_duration_milliseconds_bucket{le=\"25\",code=~\"^2..$\",service=\"$service\",path!=\"/metrics\",path!=\"/health\", pod=~\".*mirror.*\"}[5m]))\n+\n  sum(rate(api_request_duration_milliseconds_bucket{le=\"100\",code=~\"^2..$\",service=\"$service\",path!=\"/metrics\",path!=\"/health\", pod=~\".*mirror.*\"}[5m]))\n) / 2 / sum(rate(api_request_duration_milliseconds_count{service=\"$service\",path!=\"/metrics\",path!=\"/health\", pod=~\".*mirror.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Errors %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_all_errors_total{service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod=~\".*mirror.*\"})/sum(api_all_request_total{service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod=~\".*mirror.*\"})* 100"
    }
   ]
  },
  {
   "title": "Requests in Processing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_all_request_in_processing_total{service=\"$service\",path!=\"/metrics\",path!=\"/health\", pod!~\".*mirror.*\"})"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nodejs_process_cpu_usage_percentage{service=\"$service\", pod!~\".*mirror.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_process_memory_rss_bytes{service=\"$service\", pod!~\".*mirror.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Requests in Processing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_all_request_in_processing_total{service=\"$service\",path!=\"/metrics\",path!=\"/health\", pod!~\".*mirror.*\"})"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nodejs_process_cpu_usage_percentage{service=\"$service\", pod=~\".*mirror.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_process_memory_rss_bytes{service=\"$service\", pod=~\".*mirror.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request duration rate (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (irate(api_request_duration_milliseconds_bucket{service=\"$service\",path!=\"/metrics\",path!=\"/health\", pod!~\".*mirror.*\"}[5m])))/1000",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (irate(api_request_duration_milliseconds_bucket{service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod!~\".*mirror.*\"}[5m])))/1000",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (irate(api_request_duration_milliseconds_bucket{service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod!~\".*mirror.*\"}[5m])))/1000",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Request duration rate (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (irate(api_request_duration_milliseconds_bucket{service=\"$service\",path!=\"/metrics\",path!=\"/health\", pod=~\".*mirror.*\"}[5m])))/1000",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (irate(api_request_duration_milliseconds_bucket{service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod=~\".*mirror.*\"}[5m])))/1000",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (irate(api_request_duration_milliseconds_bucket{service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod=~\".*mirror.*\"}[5m])))/1000",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum (irate(api_request_total{service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod!~\".*mirror.*\"}[5m]))",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum (irate(api_request_total{code=~\"^5..$\",service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod!~\".*mirror.*\"}[5m]))",
     "legendFormat": "5XX Errors Rate"
    },
    {
     "expr": "sum (irate(api_request_total{code=~\"^4..$\",service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod!~\".*mirror.*\"}[5m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum (irate(api_request_total{code=~\"^2..$\",service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod!~\".*mirror.*\"}[5m]))",
     "legendFormat": "2XX Success Rate"
    }
   ]
  },
  {
   "title": "Slowest Cache Retrieval By Query Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(response_cache_time_bucket{pod=~\".*mirror.*\"}) by (le, operationName))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate by Method (per sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(method) (irate(api_request_total{service=\"$service\",pod!~\".*mirror.*\"}[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cache retrieval time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(response_cache_time_bucket{pod=~\".*mirror.*\"}) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(response_cache_time_bucket{pod=~\".*mirror.*\"}) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(response_cache_time_bucket{pod=~\".*mirror.*\"}) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(response_cache_time_bucket{pod=~\".*mirror.*\"}) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(1, sum(response_cache_time_bucket{pod=~\".*mirror.*\"}) by (le))",
     "legendFormat": "P100"
    },
    {}
   ]
  },
  {
   "title": "Apdex Score: target 25ms, tolerated: 100ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(irate(api_request_duration_milliseconds_bucket{le=\"25\",code=~\"^2..$\",service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod!~\".*mirror.*\"}[5m]))\n+\n  (sum(irate(api_request_duration_milliseconds_bucket{le=\"100\",code=~\"^2..$\",service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod!~\".*mirror.*\"}[5m]))/2)\n) / sum(irate(api_request_duration_milliseconds_count{service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod!~\".*mirror.*\"}[5m]))",
     "legendFormat": "Apex Score: starget 25ms, tolerated 100ms"
    }
   ]
  },
  {
   "title": "Response Cache rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(response_cache_hit_count{service=\"contentGateway\", pod=~\".*mirror.*\"}[5m]))",
     "legendFormat": "Cache hits"
    },
    {
     "expr": "sum(rate(response_cache_miss_count{service=\"contentGateway\", pod=~\".*mirror.*\"}[5m]))",
     "legendFormat": "Cache Miss"
    },
    {
     "expr": "sum(rate(response_cache_rebuild_count{service=\"contentGateway\", pod=~\".*mirror.*\"}[5m]))",
     "legendFormat": "Cache rebuilds"
    }
   ]
  },
  {
   "title": "Top 3 API calls (by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(increase(api_request_total{service=\"$service\",path!='/health',path!='/metrics',pod!~\".*mirror.*\"}[5m])) by (path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum (irate(api_request_total{service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod=~\".*mirror.*\"}[5m]))",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum (irate(api_request_total{code=~\"^5..$\",service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod=~\".*mirror.*\"}[5m]))",
     "legendFormat": "5XX Errors Rate"
    },
    {
     "expr": "sum (irate(api_request_total{code=~\"^4..$\",service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod=~\".*mirror.*\"}[5m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum (irate(api_request_total{code=~\"^2..$\",service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod=~\".*mirror.*\"}[5m]))",
     "legendFormat": "2XX Success Rate"
    }
   ]
  },
  {
   "title": "Top 3 API Error Calls ( 5XX, by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(increase(api_request_total{code=~\"^5..$\",service=\"$service\",pod!~\".*mirror.*\"}[5m])) by (path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request rate by Method (per sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(method) (irate(api_request_total{service=\"$service\",pod=~\".*mirror.*\"}[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Resolved Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "topk(10,sum(graphql_resolver_time_count{service=\"$service\", pod!~\".*mirror.*\"}) by (parentType, fieldName))",
     "legendFormat": "{{parentType}}.{{fieldName}}"
    }
   ]
  },
  {
   "title": "Apdex Score: target 25ms, tolerated: 100ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(irate(api_request_duration_milliseconds_bucket{le=\"25\",code=~\"^2..$\",service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod=~\".*mirror.*\"}[5m]))\n+\n  (sum(irate(api_request_duration_milliseconds_bucket{le=\"100\",code=~\"^2..$\",service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod=~\".*mirror.*\"}[5m]))/2)\n) / sum(irate(api_request_duration_milliseconds_count{service=\"$service\",path!=\"/metrics\",path!=\"/health\",pod=~\".*mirror.*\"}[5m]))",
     "legendFormat": "Apex Score: starget 25ms, tolerated 100ms"
    }
   ]
  },
  {
   "title": "Resolver Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(3 ,histogram_quantile(0.95,  sum(graphql_resolver_time_bucket{service=\"$service\",pod!~\".*mirror.*\"}) by (le, parentType, fieldName)))",
     "legendFormat": "{{parentType}}.{{fieldName}}"
    }
   ]
  },
  {
   "title": "Top 3 API calls (by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(increase(api_request_total{service=\"$service\",path!='/health',path!='/metrics',pod=~\".*mirror.*\"}[5m])) by (path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Top 3 API Error Calls ( 5XX, by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(increase(api_request_total{code=~\"^5..$\",service=\"$service\",pod=~\".*mirror.*\"}[5m])) by (path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Unresolved queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_resolved{service=\"$service\",pod=~\".*mirror.*\"}[5m])) - sum(increase(graphql_queries_execution_started{service=\"$service\",pod=~\".*mirror.*\"}[5m]))",
     "legendFormat": "Unresolved Queries {{operation}}.{{operationName}}"
    }
   ]
  },
  {
   "title": "Resolvers ran by attribute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "sum(increase(graphql_resolver_time_count{service=\"contentGateway\", pod=~\".*mirror.*\"}[5m])) by (parentType, fieldName)",
     "legendFormat": "{{parentType}}.{{fieldName}}"
    }
   ]
  },
  {
   "title": "Resolved Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "topk(10,sum(graphql_resolver_time_count{service=\"$service\", pod=~\".*mirror.*\"}) by (parentType, fieldName))",
     "legendFormat": "{{parentType}}.{{fieldName}}"
    }
   ]
  },
  {
   "title": "Resolver Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(15 ,histogram_quantile(0.95,  sum(graphql_resolver_time_bucket{service=\"$service\",pod=~\".*mirror.*\"}) by (le, parentType, fieldName)))",
     "legendFormat": "{{parentType}}.{{fieldName}}"
    }
   ]
  }
 ]
}