{
 "title": "Content-Sync",
 "tags": [ "Content" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Currently Running Syncs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  tocs_public_key,\n  status,\n  created_at,\n  completed_at,\n  retries, id\nFROM jobs\nWHERE\n  started_at IS NOT NULL AND\n  status != 'sync.completed'::sync_steps AND\n  status != 'sync.aborted'::sync_steps AND\n  status != 'sync.failed'::sync_steps AND\n  status != 'sync.rejected'::sync_steps\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Recently Completed Sync",
   "type": "table",
   "description": "WIP",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  completed_at AS \"time\",\n  tocs_public_key,\n  id,\n  created_at,\n  started_at,\n  status,\n  details\nFROM jobs\nWHERE\n  $__timeFilter(completed_at) AND\n  completed_at IS NOT NULL AND (\n    status = 'sync.completed'::sync_steps OR\n    status = 'sync.aborted'::sync_steps OR\n    status = 'sync.failed'::sync_steps OR\n    status = 'sync.rejected'::sync_steps\n  )\n  \nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Currently running time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  started_at AS \"time\",\n  EXTRACT(EPOCH FROM (now() - started_at)) as \"Current Runtime\",\n  tocs_public_key\nFROM jobs\nWHERE\n  $__timeFilter(started_at) and \n  status != 'sync.completed'::sync_steps AND\n  status != 'sync.aborted'::sync_steps AND\n  status != 'sync.failed'::sync_steps AND\n  status != 'sync.rejected'::sync_steps\nORDER BY 1\n-- EPOCH FROM '04:30:25'::time"
    }
   ]
  },
  {
   "title": "Time in Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  started_at AS \"time\",\n  tocs_public_key,\n  EXTRACT(EPOCH FROM (completed_at - started_at)) as \"Time In Process\"\nFROM jobs\nWHERE\n  $__timeFilter(started_at)\nORDER BY 1\n\n-- EPOCH FROM '04:30:25'::time"
    }
   ]
  }
 ]
}