{
 "title": "District Overview",
 "description": "Provides some district oversight",
 "tags": [ "rostering" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "districtShortCode", "label": "District Short Code", "query": "GGUSD" }
  ]
 },
 "panels": [
  {
   "title": "District Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT name from profiles_district\nWhere short_code='$districtShortCode'\n"
    }
   ]
  },
  {
   "title": "User Breakdown by Role",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT role, count(role) from profiles_user\nWHERE district_id=(\n  SELECT\n    id\n  FROM profiles_district\n  WHERE short_code='$districtShortCode'\n)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Roster Settings",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n *\nFROM profiles_rostersettings\nwhere district_id in (select id from public.profiles_district\nWHERE short_code = '$districtShortCode');"
    }
   ]
  },
  {
   "title": "District Summary",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "select summary from jobs\nWHERE\n  district_short_code = '$districtShortCode' AND\n  $__timeFilter(created_at) \n  order by created_at desc limit 1;\n"
    },
    {
     "rawSql": "select summary from jobs\nWHERE\n  district_short_code = '$districtShortCode'AND\n  $__timeFilter(created_at)\n  order by created_at desc limit 1;"
    },
    {
     "rawSql": "select summary from jobs\nWHERE\n  district_short_code = '$districtShortCode'AND\n  $__timeFilter(started_at)\n  order by created_at desc limit 1;\n  \n"
    }
   ]
  },
  {
   "title": "District Admin Contact Details",
   "type": "table",
   "description": "WIP - will contain DAO",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT email, username, role from profiles_user\nWHERE\nrole='DISTRICT_OWNER' AND \ndistrict_id=(\n  SELECT\n    id\n  FROM profiles_district\n  WHERE short_code='$districtShortCode'\n)\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "District Details",
   "type": "table",
   "description": "WIP - district details for name shortcode year etc.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "District Rostering Error Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  status, count(\"status\") as \"count\"\nFROM\n  jobs\nWHERE\n  status in ('completed', 'errored', 'aborted') and district_short_code = '$districtShortCode'\n  group by 1"
    },
    {
     "rawSql": "SELECT\n  status, count(\"status\") as \"count\"\nFROM\n  jobs\nWHERE\n  status in ('completed', 'errored', 'aborted') and district_short_code = '$districtShortCode'\n  group by 1"
    },
    {
     "rawSql": "SELECT\n  status, count(\"status\") as \"count\"\nFROM\n  jobs\nWHERE\n  status in ('completed', 'errored', 'aborted') and district_short_code = '$districtShortCode'\n  group by 1"
    }
   ]
  },
  {
   "title": "Average and current processing times",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select EXTRACT(EPOCH FROM (ended_at - created_at)) as \"Most recent job run\", 'CSV' as \"Source\" from jobs\nWHERE\n  district_short_code='$districtShortCode'\nORDER BY created_at desc\nlimit 1;"
    },
    {
     "rawSql": "select avg(EXTRACT(EPOCH FROM (ended_at - created_at))) as \"Average time to process\", 'CSV' as \"Source\" from jobs\nWHERE\n  district_short_code='$districtShortCode'\n  and $__timeFilter(created_at);"
    },
    {
     "rawSql": "select EXTRACT(EPOCH FROM (completed_at - started_at)) as \"Most recent job run\", 'Clever' as \"Source\" from jobs\nWHERE\n  district_short_code='$districtShortCode'\nORDER BY created_at desc\nlimit 1;"
    },
    {
     "rawSql": "select avg(EXTRACT(EPOCH FROM (completed_at - started_at))) as \"Average time to process\", 'Clever' as \"Source\" from jobs\nWHERE\n  district_short_code='$districtShortCode'and $__timeFilter(started_at);"
    },
    {
     "rawSql": "select EXTRACT(EPOCH FROM (completed_at - started_at)) as \"Most recent job run\", 'Classlink' as \"Source\" from jobs\nWHERE\n  district_short_code='$districtShortCode' \nORDER BY created_at desc\nlimit 1;"
    },
    {
     "rawSql": "select avg(EXTRACT(EPOCH FROM (completed_at - started_at))) as \"Average time to process\", 'Classlink' as \"Source\" from jobs\nWHERE\n  district_short_code='$districtShortCode'and $__timeFilter(started_at);"
    }
   ]
  },
  {
   "title": "Last 10 jobs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select id as \"Job Id\", district_short_code as \"Shortcode\", status as \"Status\", created_at as \"Created At\", started_at as \"Started At\", 'Classlink' as \"Source\", EXTRACT(EPOCH FROM (completed_at - started_at)) as \"Time to process\" from jobs\nWHERE\n  district_short_code='$districtShortCode'\n  order by started_at desc\nlimit 10;"
    },
    {
     "rawSql": "select id as \"Job Id\", district_short_code as \"Shortcode\", status as \"Status\", created_at as \"Started At\", 'CSV' as \"Source\", EXTRACT(EPOCH FROM (ended_at - created_at)) as \"Time to process\" from jobs\nWHERE\n  district_short_code='$districtShortCode'\n  order by created_at desc\nlimit 10;"
    },
    {
     "rawSql": "select id as \"Job Id\", district_short_code as \"Shortcode\", status as \"Status\", created_at as \"Created At\",  started_at as \"Started At\", 'Clever' as \"Source\", EXTRACT(EPOCH FROM (completed_at - started_at)) as \"Time to process\"   from jobs\nWHERE\n  district_short_code='$districtShortCode'\n  order by started_at desc\nlimit 10;"
    }
   ]
  },
  {
   "title": "Subscription Details",
   "type": "table",
   "description": "WIP",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "select \npr.\"name\", \"shortCode\", \"isActive\", \"salesforceAccount\", \"expiresOn\", \"isTest\", \"isTrial\", \"purchaserId\", \"opportunityType\", \"purchasedAt\", \"salesforceOpportunity\", p.\"isAvailable\", pv.\"productVariantCode\", \"productCode\", pv.\"name\" as \"prodname\", \"description\", pv.\"isAvailable\" as \"Variant Is available\", \"tocsApp\", \"territoryCode\", \"territoryName\"\nfrom \"Purchaser\" pr, \"Purchase\" p, \"ProductVariant\" pv where pr.\"shortCode\" = '$districtShortCode' and p.\"purchaserId\"=pr.\"id\" and pv.\"productVariantCode\" = p.\"productVariantCode\";\n"
    }
   ]
  },
  {
   "title": "District Users",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "\nselect * from public.profiles_user where district_id in (select id from public.profiles_district\nWHERE short_code = '$districtShortCode');"
    }
   ]
  }
 ]
}