{
 "title": "Duplicate social accounts found",
 "tags": [
  "duplicate",
  "social",
  "authentication",
  "rostering"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "userGuid", "label": "Auth UserId" },
   { "name": "isUserActive", "label": "Check if user is active " }
  ]
 },
 "panels": [
  {
   "title": "Duplicate social accounts found",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select u.id as \"AuthID\", u.email as \"AuthEmail\",u.last_login as \"Last Login\", u.date_joined as \"Date Joined\", s.extra_data  from socialaccount_socialaccount as s left outer join profiles_user as u \non s.user_id=u.id where s.user_id in (\n    select u.id from profiles_user as u inner join socialaccount_socialaccount as s on s.user_id = u.id group by u.id having count(u.id) > 1\n);"
    }
   ]
  },
  {
   "title": "User Detail",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select u.id, u.email, s.extra_data from socialaccount_socialaccount as s inner join profiles_user as u \non s.user_id=u.id where u.id::text='${userGuid}'"
    }
   ]
  },
  {
   "title": "Is user Active?",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select id, email, is_active from profiles_user where email='${isUserActive}';"
    }
   ]
  }
 ]
}