{
 "title": "Lesson Answer Service Dashboard",
 "tags": [
  "performance",
  "analytics"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Answer save P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(api_request_duration_milliseconds_bucket{method=\"PUT\",code=\"200\",service=\"lesson-answers-service\"}[5m])))/1000",
     "legendFormat": "Save Answer Rest P95"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(api_websocket_duration_seconds_bucket{service=\"lesson-answers-service\",method=\"upsertAnswer\"}[5m])))\n",
     "legendFormat": "Save Answer Websocket P95"
    }
   ]
  },
  {
   "title": "REST Saved Answers Response Time (ms)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_request_duration_milliseconds_bucket{method=\"PUT\",code=\"200\",service=\"lesson-answers-service\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "WebSockets Saved Answers Response Time (ms)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_websocket_duration_seconds_bucket{method=\"upsertAnswer\",service=\"lesson-answers-service\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total REST Requests/Response Time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(api_request_duration_milliseconds_bucket{method=\"PUT\",code=\"200\",service=\"lesson-answers-service\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total WS Requests/Response Time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(api_websocket_duration_seconds_bucket{method=\"upsertAnswer\",service=\"lesson-answers-service\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Throughput (Rest)",
   "type": "timeseries",
   "description": "Request per second going through rest endpoints",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(api_request_total{service=\"lesson-answers-service\",path!=\"/health\",path!=\"/metrics\"}[5m]))",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "Throughput (WS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(irate(api_websocket_total{service=\"lesson-answers-service\"}[5m]))\n",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "Memory Usage Per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_process_memory_heap_used_bytes{service=\"lesson-answers-service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Websocket Connections per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "api_websocket_connections{service=\"lesson-answers-service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "nodejs_process_cpu_usage_percentage{service=\"lesson-answers-service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Websocket connections Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "sum(api_websocket_connections{service=\"lesson-answers-service\"})",
     "legendFormat": "Websocket Connections"
    }
   ]
  }
 ]
}