{
 "title": "Node HTTP playground",
 "description": "Swagger-Stats Main Dashboard Revision  3",
 "tags": [ "wip" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "service", "query": { "query": "label_values(service)" } },
   { "name": "app", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "title": "Most resolvers called",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,sum(graphql_resolver_time_count) by (parentType,fieldName))",
     "legendFormat": "{{parentType}}.{{fieldName}}"
    }
   ]
  },
  {
   "title": "Slowest resolvers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(3 ,histogram_quantile(0.95,  sum(graphql_resolver_time_bucket{pod!~\".*mirror.*\"}) by (le, parentType, fieldName)))",
     "legendFormat": "{{parentType}}.{{fieldName }}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket{app=\"$app\"}[5m]))by (le))"
    }
   ]
  },
  {
   "title": "Requests in Processing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_all_request_in_processing_total{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_process_cpu_usage_percentage{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Heap Used, Mb",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "expr": "(nodejs_process_memory_heap_used_bytes{service=\"$service\"})/1048576"
    }
   ]
  },
  {
   "title": "Request rate by Method (per sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(method) (irate(api_request_total{service=\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_all_request_total{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(api_request_duration_milliseconds_bucket{le=\"25\",code=~\"^2..$\",service=\"$service\"}[5m]))\n+\n  sum(rate(api_request_duration_milliseconds_bucket{le=\"100\",code=~\"^2..$\",service=\"$service\"}[5m]))\n) / 2 / sum(rate(api_request_duration_milliseconds_count{service=\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Errors %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_all_errors_total{service=\"$service\"}/api_all_request_total{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Request Duration (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"5\",service=\"$service\",path!=\"/metrics\",path!=\"/health\"}[5m])) /  sum(irate(api_request_duration_milliseconds_count{service=\"$service\",path!=\"/metrics\",path!=\"/health\"}[5m])) ) * 100",
     "legendFormat": "Duration < 5ms (%)"
    },
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"10\",service=\"$service\",path!=\"/metrics\",path!=\"/health\"}[5m])) /  sum(irate(api_request_duration_milliseconds_count{service=\"$service\",path!=\"/metrics\",path!=\"/health\"}[5m])) ) * 100",
     "legendFormat": "Duration < 10ms (%)"
    },
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"50\",service=\"$service\",path!=\"/metrics\",path!=\"/health\"}[5m])) /  sum(irate(api_request_duration_milliseconds_count{service=\"$service\",path!=\"/metrics\",path!=\"/health\"}[5m])) ) * 100",
     "legendFormat": "Duration < 50ms (%)"
    },
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"100\",service=\"$service\",path!=\"/metrics\",path!=\"/health\"}[5m])) /  sum(irate(api_request_duration_milliseconds_count{service=\"$service\",path!=\"/metrics\",path!=\"/health\"}[5m])) ) * 100",
     "legendFormat": "Duration < 100ms (%)"
    }
   ]
  },
  {
   "title": "Request and Error Rates (per sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(api_request_total{service=\"$service\"}[5m]))",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum (irate(api_request_total{code=~\"^5..$\",service=\"$service\"}[5m]))",
     "legendFormat": "5XX Errors Rate"
    },
    {
     "expr": "sum (irate(api_request_total{code=~\"^4..$\",service=\"$service\"}[5m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum (irate(api_request_total{code=~\"^2..$\",service=\"$service\"}[5m]))",
     "legendFormat": "2XX Success Rate"
    }
   ]
  },
  {
   "title": "Top 3 API Error Calls ( 5XX, by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(irate(api_request_total{code=~\"^5..$\",service=\"$service\"}[5m])) by (path))"
    }
   ]
  },
  {
   "title": "Apdex Score: target 25ms, tolerated: 100ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(irate(api_request_duration_milliseconds_bucket{le=\"25\",code=~\"^2..$\",service=\"$service\"}[5m]))\n+\n  (sum(irate(api_request_duration_milliseconds_bucket{le=\"100\",code=~\"^2..$\",service=\"$service\"}[5m]))/2)\n) / sum(irate(api_request_duration_milliseconds_count{service=\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top 3 API calls (by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(irate(api_request_total{service=\"$service\",path!='/health',path!='/metrics'}[5m])) by (path))"
    }
   ]
  }
 ]
}