{
 "title": "Node HTTP Service Dashboard",
 "description": "Disha Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket, service)"
    }
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket, le)"
    }
   },
   {
    "name": "tolerated",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket, le)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests rate over time range",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=\"$service\", path!=\"/health\", path!=\"metrics\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(http_request_duration_seconds_bucket{le=\"$target\",status_code=~\"^[2,3]..$\", service=\"$service\", path!=\"/health\"}) +\n  (\n    sum(http_request_duration_seconds_bucket{le=\"$tolerated\",status_code=~\"^[2,3]..$\", service=\"$service\", path!=\"/health\"}) -\n    sum(http_request_duration_seconds_bucket{le=\"$target\",status_code=~\"^[2,3]..$\", service=\"$service\", path!=\"/health\"})\n  )/2\n) \n/ sum(http_request_duration_seconds_count{service=\"$service\", path!=\"/health\"})"
    }
   ]
  },
  {
   "title": "Errors %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    (sum (http_request_duration_seconds_count{status_code=~\"^5..$\", service=\"$service\",service=\"$service\", path!=\"/health\", path!=\"/metrics\"}) +  (sum (http_request_duration_seconds_count{status_code=~\"^4..$\", service=\"$service\",service=\"$service\", path!=\"/health\", path!=\"/metrics\"})))/ sum (http_request_duration_seconds_count{service=\"$service\", path!=\"/health\", path!=\"/metrics\"}))"
    }
   ]
  },
  {
   "title": "GQL Resolver invocation rate over time range",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(graphql_resolver_time_count{service=\"$service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{service=\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request and Error Rates (per sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(http_request_duration_seconds_count{service=\"$service\", path!=\"/health\"}[5m]))",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum (irate(http_request_duration_seconds_count{status_code=~\"^5..$\", service=\"$service\", path!=\"/health\"}[5m]))",
     "legendFormat": "5XX Errors Rate"
    },
    {
     "expr": "sum (irate(http_request_duration_seconds_count{status_code=~\"^4..$\", service=\"$service\", path!=\"/health\"}[5m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum (irate(http_request_duration_seconds_count{status_code=~\"^2..$\", service=\"$service\", path!=\"/health\"}[5m]))",
     "legendFormat": "2XX Success Rate"
    },
    {
     "expr": "sum (irate(http_request_duration_seconds_count{status_code=~\"^3..$\", service=\"$service\", path!=\"/health\"}[5m]))",
     "legendFormat": "3XX Success Rate"
    }
   ]
  },
  {
   "title": "Request rate by Method (per sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(method) (rate(http_request_duration_seconds_sum{service=\"$service\"}[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(http_request_duration_seconds_bucket{le=\"$target\",status_code=~\"^[2,3]..$\", service=\"$service\", path!=\"/health\"}) +\n  (\n    sum(http_request_duration_seconds_bucket{le=\"$tolerated\",status_code=~\"^[2,3]..$\", service=\"$service\", path!=\"/health\"}) -\n    sum(http_request_duration_seconds_bucket{le=\"$target\",status_code=~\"^[2,3]..$\", service=\"$service\", path!=\"/health\"})\n  )/2\n) \n/ sum(http_request_duration_seconds_count{service=\"$service\", path!=\"/health\"})",
     "legendFormat": "Apdex Score"
    }
   ]
  },
  {
   "title": "Request Duration(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (irate(http_request_duration_seconds_bucket{service=\"$service\",path!=\"/metrics\",path!=\"/health\"}[5m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (irate(http_request_duration_seconds_bucket{service=\"$service\",path!=\"/metrics\",path!=\"/health\"}[5m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (irate(http_request_duration_seconds_bucket{service=\"$service\",path!=\"/metrics\",path!=\"/health\"}[5m])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Top 10 API calls (by path) In Last 24 hours",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10,sum(max_over_time(http_request_duration_seconds_count{service=\"$service\", path!='/health'}[$__interval])- min_over_time(http_request_duration_seconds_count{service=\"$service\", path!='/health'}[24h])) by (method, path, status_code))",
     "legendFormat": "{{method}} {{path}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Top 10 API Error Calls ( 5XX and 4XX, by path)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(max_over_time(http_request_duration_seconds_count{code=~\"^5..$\", service=\"$service\", path!='/health'}[6s])- min_over_time(http_request_duration_seconds_count{code=~\"^5..$\", service=\"$service\", path!='/health'}[24h])) by (method, path))",
     "legendFormat": "{{method}} /{{path}} 5XX"
    },
    {
     "expr": "topk(10,sum(max_over_time(http_request_duration_seconds_count{status_code=~\"^[4,5]..$\", service=\"$service\"}[6s])- min_over_time(http_request_duration_seconds_count{status_code=~\"^[4,5]..$\", service=\"$service\"}[24h])) by (method, path))",
     "legendFormat": "{{method}} {{path}} 4XX"
    }
   ]
  },
  {
   "title": "GraphQL Resolver Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(graphql_resolver_time_count{service=\"$service\"}[5m])) by (parentType)",
     "legendFormat": "{{parentType}}"
    }
   ]
  },
  {
   "title": "Slowest Average Resolver Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (parentType, fieldName) (rate(graphql_resolver_time_sum{service=\"$service\"}[$__interval])/rate(graphql_resolver_time_count{service=\"$service\"}[$__interval]))",
     "legendFormat": "{{parentType}} - {{fieldName}}"
    }
   ]
  },
  {
   "title": "Prisma Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by (service) (rate(query_total_queries{service=\"$service\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB connection pool usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "sum(pool_idle_connections{service=\"$service\"})",
     "legendFormat": "Idle Connections"
    },
    {
     "expr": "sum(pool_active_connections{service=\"$service\"})",
     "legendFormat": "Active connections"
    },
    {
     "expr": "sum(rate(pool_wait_count{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "Waiting Connections"
    }
   ]
  },
  {
   "title": "Average Prisma Query Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(query_total_elapsed_time_ms_sum{service=\"$service\"}[$__interval])/rate(query_total_elapsed_time_ms_count{service=\"$service\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method, path) (rate(http_request_duration_seconds_sum{service=\"$service\", path!=\"/health\"}[$__interval])/rate(http_request_duration_seconds_count{service=\"$service\", path!=\"/health\"}[$__interval]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}