{
 "title": "Pods Status",
 "tags": [
  "kubernetes",
  "reporting"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Running Pods",
   "type": "stat",
   "description": "Shows the number of Running pods in a cluster",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "description": "Shows the number of failed pods in a cluster",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(kube_pod_status_phase{phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Unknown Pods",
   "type": "stat",
   "description": "Shows the number of failed pods in a cluster",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(kube_pod_status_phase{phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "stat",
   "description": "Shows the number of failed pods in a cluster",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(kube_pod_status_phase{phase!=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Succeeded Pods",
   "type": "stat",
   "description": "Shows the number of failed pods in a cluster",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(kube_pod_status_phase{phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods restarts",
   "type": "gauge",
   "gridPos": { "h": 18, "w": 15, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total!=0",
     "legendFormat": "{{namespace}} {{pod}}"
    }
   ]
  }
 ]
}