{
 "title": "Rostering services",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "pod", "query": "or-worker" },
   { "name": "classlinkpod", "query": "rostering-classlink-wrk" }
  ]
 },
 "panels": [
  {
   "title": "Classlink RSS memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{pod=~\".*$classlinkpod.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Classlink CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{pod=~\".*$classlinkpod.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "or-worker CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{pod=~\".*$pod.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "or-worker RSS memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{pod=~\".*$pod.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}