{
 "title": "Rostering Job Monitoring",
 "tags": [
  "rostering",
  "analytics"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "shortcode" },
   { "name": "datasource", "query": "postgres" },
   { "name": "or_worker", "query": "ts-rostering-or-worker" },
   { "name": "classlink_worker", "query": "rostering-classlink-wrk" },
   { "name": "clever_worker", "query": "rostering-clever-wrk" }
  ]
 },
 "panels": [
  {
   "title": "Currently in Process",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"district_name\" as \"District Name\",\n  \"district_short_code\" as \"District Shortcode\",\n  \"id\" as \"Job ID\",\n  \"status\" as \"Status\",\n  \"created_at\" as \"Created At\",\n  \"started_at\" as \"Started At\"\nFROM\n  jobs\nWHERE\n  status not in ('completed', 'errored', 'aborted')\n  AND $__timeFilter(created_at)\nORDER BY\n  \"Started At\" asc,\n  \"Created At\" asc;\n"
    }
   ]
  },
  {
   "title": "Time to process job",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  started_at AS \"time\",\n  district_short_code,\n  EXTRACT(EPOCH FROM (completed_at - started_at)) as \"Time In Process\"\nFROM jobs\nWHERE\n  $__timeFilter(started_at)\nORDER BY 1\n\n-- EPOCH FROM '04:30:25'::time"
    },
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  district_short_code,\n  EXTRACT(EPOCH FROM (ended_at - created_at)) as \"Time In Process\"\nFROM jobs\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1\n\n-- EPOCH FROM '04:30:25'::time"
    },
    {
     "rawSql": "SELECT\n  started_at AS \"time\",\n  district_short_code,\n  EXTRACT(EPOCH FROM (completed_at - started_at)) as \"Time In Process\"\nFROM jobs\nWHERE\n  $__timeFilter(started_at)\nORDER BY 1\n\n-- EPOCH FROM '04:30:25'::time"
    }
   ]
  },
  {
   "title": "All recently scheduled jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select id as \"Job Id\", district_name as \"District Name\", district_short_code as \"Shortcode\", status as \"Status\", created_at as \"Created At\", started_at as \"Started At\", 'Classlink' as \"Source\", EXTRACT(EPOCH FROM (completed_at - started_at)) as \"Time to process\" from jobs\nWHERE\n  $__timeFilter(created_at);"
    },
    {
     "rawSql": "select id as \"Job Id\", district_name as \"District Name\", district_short_code as \"Shortcode\", status as \"Status\", created_at as \"Started At\", 'CSV' as \"Source\", EXTRACT(EPOCH FROM (ended_at - created_at)) as \"Time to process\" from jobs\nWHERE\n  $__timeFilter(created_at);"
    },
    {
     "rawSql": "select id as \"Job Id\", district_name as \"District Name\", district_short_code as \"Shortcode\", status as \"Status\", created_at as \"Created At\",  started_at as \"Started At\", 'Clever' as \"Source\", EXTRACT(EPOCH FROM (completed_at - started_at)) as \"Time to process\"   from jobs\nWHERE\n  $__timeFilter(created_at);"
    }
   ]
  },
  {
   "title": "All recently failed jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 12 },
   "targets": [
    {
     "rawSql": "select id as \"Job Id\", district_name as \"District Name\", district_short_code as \"Shortcode\", status as \"Status\", created_at as \"Created At\", started_at as \"Started At\", 'Classlink' as \"Source\", EXTRACT(EPOCH FROM (completed_at - started_at)) as \"Time to process\" from jobs\nWHERE\n  $__timeFilter(created_at) and (status='errored' OR status='aborted');"
    },
    {
     "rawSql": "select id as \"Job Id\", district_name as \"District Name\", district_short_code as \"Shortcode\", status as \"Status\", created_at as \"Started At\", 'CSV' as \"Source\", EXTRACT(EPOCH FROM (ended_at - created_at)) as \"Time to process\" from jobs\nWHERE\n  $__timeFilter(created_at) and (status='errored');"
    },
    {
     "rawSql": "select id as \"Job Id\", district_name as \"District Name\", district_short_code as \"Shortcode\", status as \"Status\", created_at as \"Created At\",  started_at as \"Started At\", 'Clever' as \"Source\", EXTRACT(EPOCH FROM (completed_at - started_at)) as \"Time to process\"   from jobs\nWHERE\n  $__timeFilter(created_at) and (status='errored' OR status='aborted' );"
    }
   ]
  },
  {
   "title": "Job by shortcode",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "select * from jobs\nWHERE\n  district_short_code = '$shortcode'AND \n  $__timeFilter(created_at);\n"
    },
    {
     "rawSql": "select * from jobs\nWHERE\n  district_short_code = '$shortcode' AND \n  $__timeFilter(created_at);\n"
    },
    {
     "rawSql": "select * from jobs\nWHERE\n  district_short_code = '$shortcode' AND \n  $__timeFilter(created_at);\n"
    }
   ]
  },
  {
   "title": "Classlink-worker CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 20 },
   "targets": [
    {
     "expr": "sum(container_cpu_load_average_10s{pod=~\".*$classlink_worker.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "or-worker CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(container_cpu_load_average_10s{pod=~\".*$or_worker.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Clever-worker CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(container_cpu_load_average_10s{pod=~\".*$clever_worker.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "or-worker RSS memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\".*$or_worker.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "All recently failed jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select COUNT(*), status, created_at as \"time\", district_short_code from jobs\nWHERE\n  $__timeFilter(created_at) and (status='errored' OR status='aborted')\n  GROUP BY 2,3,4;"
    },
    {
     "rawSql": "select COUNT(*), status, created_at as \"time\", district_short_code  from jobs\nWHERE\n  $__timeFilter(created_at) and status='errored'\n  GROUP BY 2,3,4;\n  "
    },
    {
     "rawSql": "select COUNT(*), status, created_at as \"time\", district_short_code  from jobs\nWHERE\n  $__timeFilter(created_at) and (status='errored' OR status='aborted')\n  GROUP BY 2,3,4;"
    }
   ]
  },
  {
   "title": "Classlink-worker RSS memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\".*$classlink_worker.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Clever-worker RSS memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\".*$clever_worker.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}