{
 "title": "Sentry: Events",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sentry Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Client API Responses by API version",
   "type": "graph",
   "description": "Responses from client api by version and status",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Events Processed by Language",
   "type": "graph",
   "description": "Events Processed by Sentry",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sentry_events_processed_total{env=\"ops\"}[$__interval])",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "Total number of started and processed jobs",
   "type": "graph",
   "description": "Total number of jobs started and finished.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sentry_jobs_started_total{env=\"ops\"}[$__interval])",
     "legendFormat": "Started"
    },
    {
     "expr": "rate(sentry_jobs_finished_total{env=\"ops\"}[$__interval])",
     "legendFormat": "Finished"
    }
   ]
  },
  {
   "title": "Event Latency",
   "type": "heatmap",
   "description": "Responses from client api by version and status",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (le) (rate(sentry_events_latency_seconds_bucket{env=\"ops\"}[$__interval]))",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}