{
 "title": "Users Last Login",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   { "name": "Short_Code" }
  ]
 },
 "panels": [
  {
   "title": "Total Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "Select tt.role, Count (tt.date)\nFrom (Select a.id as user_ID, date(a.last_login), a.role\nFrom profiles_user as a join profiles_district as b on a.district_id = b.id\nWhere a.is_active = '1'\nand a.district_id = b.id\nand b.is_trial <> 'true'\nand b.is_pilot <> 'true'\nand $__timeFilter(a.last_login)\nand a.role <> 'SCHOOL_ADMIN'\nand a.role <> 'DISTRICT_OWNER'\nand b.is_automated_test_district <> 'true') as tt\nGroup by tt.role\nHAVING Count (tt.date) >'1'\nOrder by tt.role\n"
    }
   ]
  },
  {
   "title": "Last Student Login",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "Select a.id as students, a.last_login, b.name, b.id as district_id\nFrom profiles_user as a join profiles_district as b on a.district_id = b.id\nWhere a.role = 'STUDENT'\nand a.is_active = '1'\nand a.district_id = b.id\nand b.is_trial = false\nand b.is_pilot = false\nand b.is_automated_test_district = false\nand a.last_login is not NULL\nand a.is_test_user = false\nand a.email not like '%twigeducation%'\nand a.email not like '%twig-%'\nand $__timeFilter(a.last_login)\n"
    }
   ]
  },
  {
   "title": "Count of User Logins by District",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "Select tt.name, tt.district_id, tt.role, Count (tt.last_login)\nFrom (Select a.id as user_ID, a.last_login, b.name, b.id as district_id, a.role\nFrom profiles_user as a join profiles_district as b on a.district_id = b.id\nWhere a.is_active = '1'\nand a.district_id = b.id\nand b.is_trial = 'false'\nand b.is_pilot = 'false'\nand $__timeFilter(a.last_login)\nand b.is_automated_test_district = 'false') as tt\nGroup by tt.name, tt.district_id, tt.role\nHAVING Count (tt.last_login) >'1'\nOrder by tt.name, tt.role\n"
    }
   ]
  },
  {
   "title": "School Names",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH x AS\n(\nSelect  a.class_id, b.user_id, c.name, c.district_id\nFrom classes a, enrollments b, orgs c\nWhere a.class_id = b.class_id\nand a.org_id = c.org_id\nand c.is_test = 'false'\nand b.is_test = 'false'\nand a.is_test = 'false')\nSELECT * FROM x\n  LIMIT 1000;"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } }
 ]
}